name: Run Python Script
on:
  workflow_dispatch: # Adds a manual "Run workflow" button
  schedule:
    - cron: '0 0 * * *' # Optional: Runs automatically every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python RockPaperScissors.py
        
      - name: Run Python Script
        uses: jannekem/run-python-script-action@v1.8
        with:
          # Python script
          script: RockPaperScissors.py
          # Fail step if the return code from running the script is non-zero
          fail-on-error: # optional, default is true
          # Include utility functions
          util: # optional, default is true
          
